### ISSUE TITLE
Impossible to run migrations on a single node

### ISSUE THREAD

**Issue by cezarykluczynski** [Contrast-Security-OSS/cassandra-migration#13]
ConsistencyLevel.ALL requires that there's at least two nodes, therefore it's impossible to run migrations on a single node. Maybe consistency level could be configurable too?

**Comment by regis-leray** [comment]
Already a pull request :)

Determine consistency level dynamically.
https://github.com/Contrast-Security-OSS/cassandra-migration/pull/9

**Comment by ntatsumi** [comment]
The PR has been merged.
